### ISSUE TITLE
Files in subfolder ignored when added before beacon can fire

### ISSUE THREAD

**Issue by arg0nik** [HubbleStack/Pulsar#20] opened 2016-08-26 23:02 UTC
Noted an issue where new files won't be noticed. In a script, I added a set of 24 new folders, each with 2000 folders inside. Only 24 events are fired, and I can then create a new file inside of any of the 2000 without it being noticed.

The reason why from previous discussions is likely that the subfolders are being added before the new 24 folders are added to the list of files watched. A fix, as discussed, would be to add logic which looks for new directory events and checks if there's files inside those new directories already.

**Comment by basepi** [comment] 2016-10-06 16:16
@greenage I'm having trouble reproducing this issue. Did you have `auto_add: True` set on the folder in which you were creating the 2000 folders?

I have a very basic config at the moment:

```
/tmp/blah: { recurse: True, auto_add: True }
return: slack_pulsar
checksum: sha256
stats: True
batch: True
```

And I run the following command, which should reproduce the issue on a smaller scale:

```
mkdir /tmp/blah/test2 && mkdir /tmp/blah/test2/test2 && mkdir /tmp/blah/test2/test2/test2
```

And I see three events. One for each directory. Thoughts?

**Comment by arg0nik** [comment] 2016-10-06 20:41
Yes, the file is currently set with  `{ recurse: True, auto_add: True }`. I'm not sure why that wouldn't reproduce the issue. Maybe it isn't at the level we had thought?

I'm running a small script that gives the behavior:

```
#!/usr/bin/env python

import os

for idx in range(1,4):
  fname = "file" + str(idx)
  os.mkdir(fname)
  fullpath = os.path.abspath(fname)
  for idx in range(1,2000):
    nested_file = fullpath + "/" + str(idx)
    os.mkdir(nested_file)
```

Only the first three files are logged in Splunk. 

Other pillar settings are:

```
return: splunk_pulsar_return 
checksum: sha256
stats: True
batch: False
```

Running Salt 2016.3.3 (Boron) with Hubblestack 2016.7.0

**Comment by basepi** [comment] 2016-10-10 20:24
I'm trying to figure out if this could be a returner issue, but I don't think so. With `batch: False`, the returner is called once per event, and if that were a problem I would expect it to be much less consistent, returning some but not all of the subdirectory events or something like that, as opposed to only returning the first layer of events.

In any case, I used your script and practically crashed slack sending it a message that was hundreds of thousands of lines long. Toned it down to 10 subdirectories instead of 2000 (much more manageable) and turned off batch, and it still worked perfectly.

What version of python-inotify are you using? Wondering if that is the culprit.

```
>>> import pyinotify
>>> pyinotify.__version__
'0.9.4'
```

**Comment by basepi** [comment] 2016-10-12 19:41
@greenage Can you get me your version of python-inotify?

**Comment by arg0nik** [comment] 2016-10-12 21:42
@basepi 

```
>>> import pyinotify
>>> pyinotify.__version__
'0.9.4'
```

I've set `batch: True`, and I believe it gave the same result. I'll double check a little later.

**Comment by basepi** [comment] 2016-10-27 22:15
Tried this again today, but using splunk as the destination. Used your original script version. Seeing all 6000 events in splunk, no problem. So I'm not sure what's going on. We may need to get together on slack and make sure we're using the same process to reproduce this. I would also recommend upgrading to the latest versions of pulsar/quasar, and setting `batch: True` in your hubblestack_pulsar_config.yaml. Pulsar has changed a fair bit since the days when it was using pillar data as its source of truth.

I'm going to close this since it appears to be working in the latest version, but we can continue to use this thread for discussion (I'll still monitor the emails) and can re-open if we find a bug.

**Closed as completed by basepi** 2016-10-27 22:15 UTC
Labels: bug, cannot reproduce
